# Generated by Django 5.0 on 2023-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.CharField(blank=True, choices=[('flute', 'Flute'), ('ektara', 'Ektara'), ('dotara', 'Dotara'), ('cymbals', 'Cymbals')], max_length=20, null=True),
        ),
    ]
