# Generated by Django 5.0 on 2023-12-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('instrument_type', models.CharField(choices=[('flute', 'Flute'), ('ektara', 'Ektara'), ('dotara', 'Dotara'), ('cymbals', 'Cymbals')], max_length=20)),
            ],
        ),
    ]
